import os

DEVICE_ENDPOINT = os.environ.get("DEVICE_ENDPOINT")

DEVICE_CONNECTION_RETRY = os.environ.get("DEVICE_CONNECTION_RETRY")
DEVICE_CONNECTION_TIMEOUT = os.environ.get("DEVICE_CONNECTION_TIMEOUT")

DEVICE_CERTIFICATES_ROOT_DIRECTORY = os.environ.get("DEVICE_CERTIFICATES_ROOT_DIRECTORY", ".")
DEVICE_PEM_FILE = f"{DEVICE_CERTIFICATES_ROOT_DIRECTORY}/certificate.pem"
DEVICE_PUBLIC_KEY_FILE = f"{DEVICE_CERTIFICATES_ROOT_DIRECTORY}/public_key.pub"
DEVICE_PRIVATE_KEY_FILE = f"{DEVICE_CERTIFICATES_ROOT_DIRECTORY}/private_key_key.priv"
ROOTCA_CERTIFICATE_FILE =  f"{DEVICE_CERTIFICATES_ROOT_DIRECTORY}/root_ca.cert"
